### ISSUE TITLE
webpack问题

### ISSUE THREAD

**Issue by sunha1yang** [zhufengnodejs/question#1]
webpack版本：`2.3.3`

#### 问题描述：

在打包的时候报某个文件没有找到

当前文件文件内肯定没有引用这个问题，这个我可以保证

#### 操作过程：
- 切换分支时容易出现这样的问题【此时编译脚本没有停止】

#### 解决过程：
- 切换到之前分支，编译，然后切换回来，再次编译就ok。

#### 疑问点：
- 想知道引起这样的原因可能有哪些？

**Comment by mcdongWang** [comment]
首先, 要确认下你得某个文件没有找到 是你的代码文件 还是 依赖包的文件

其次, 你的两个分支是否都有这个文件?

再详细描述下问题

**Comment by sunha1yang** [comment]
已解决3Q
