### ISSUE TITLE
echarts高亮事件能够设置成click事件触发吗?

### ISSUE THREAD

**Issue by zhuxinping** [zhufengnodejs/question#2]
One-line summary [问题简述]
我的问题是这样的,想实现的是类似微信运动跑步计数的那种图标,可以点击切换周榜月榜的,但是一进入页面要默认展示当前周和当前月的数据高亮,这个需求怎么实现;遇到的问题就是高亮事件是鼠标移入移出事件触发,我想实现是click点击事件触发怎么做到;

Version & Environment [版本及环境]
ECharts version [ECharts 版本]:
echarts 4.0
Browser version [浏览器类型和版本]:
谷歌浏览器
OS Version [操作系统类型和版本]:
win7
Expected behaviour [期望结果]
ECharts option [ECharts配置项]
	var option = {

		//backgroundColor: 'rgba(0,170,255,0.3)',
		grid: {
			x: '15%',
			y: '15%'
		},
		tooltip: { //鼠标悬浮弹窗提示
			trigger: 'axis',
			show: true,
			showDelay: 0,
			hideDelay: 0,
			transitionDuration: 0,
			backgroundColor: 'rgba(255,255,255,0)',
			borderColor: 'rgba(255,255,255,0)',
			//			borderRadius: 4,
			//			borderWidth: 0,
			axisPointer: { // 坐标轴指示器，坐标轴触发有效
				type: 'line', // 默认为直线，可选为：'line' | 'shadow'
				lineStyle: { // 直线指示器样式设置
					color: 'rgba(255,255,255,0)',

				},

			},
			textStyle: {
				color: 'rgba(255,151,0,1)',
				fontSize: 14
			},
			//adding: 10, // [5, 10, 15, 20]
			formatter: function(params, index, callback) {
				//console.log(params);
				var rankNum = (params[0].data);
				if(rankNum) {
					$('.rank-num').html(title + '&nbsp' + scoreList[params[0].dataIndex]);
				}
				return;
			},

		},
		title: {
			left: 'left',
			text: '',
		},
		xAxis: {
			type: 'category',
			boundaryGap: false,
			axisLine: {
				show: false
			},
			axisLabel: {
				show: true,
				textStyle: {
					color: '#BBBBBD',
					fontSize: '12'
				}
			},
			axisTick: {
				show: false
			},
			splitLine: { // grid 分割线设置
				show: true,
				lineStyle: {
					width: 1,
					type: 'dashed',
					color: ['rgba(238,238,238,1)']
				}
			},
			data: []
		},
		yAxis: {
			type: 'value',
			inverse: true,
			min: 1,
			//max:15,
			//interval: 2,
			minInterval: 1,
			axisLine: {
				show: false
			},
			axisLabel: {
				show: true,
				textStyle: {
					color: '#BBBBBD',
					fontSize: '12'
				}
			},
			axisTick: {
				show: false
			},
			splitLine: { // grid 分割线设置
				show: true,
				lineStyle: {
					width: 1,
					type: 'dashed',
					color: ['rgba(238,238,238,1)']
				}
			},

			boundaryGap: [0, '100%']
		},
		dataZoom: [{
			type: 'inside',
			start: 100,
			end: 70
		}],
		series: [{
			name: '排名',
			type: 'line',
			showSymbol: false,
			smooth: true,
			symbol: 'image://../../images/rank/dot@2x.png', //设定为实心点
			symbolSize: [10, 10], //设定实心点的大小
			sampling: 'average',
			itemStyle: {
				normal: {
					color: 'rgba(0,170,255,1)'
				},
				emphasis: {
					color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
							offset: 0,
							color: 'rgba(255,151,0,1)'
						},
						{
							offset: 0.5,
							color: 'rgba(255,151,0,0.8)'
						},
						{
							offset: 1,
							color: 'rgba(255,151,0,0.5)'
						}
					]),

					label: {
						show: true,
						triggerOn: 'click',
						formatter: [
							' {ranStyle|}第{c}名'
						].join("\n"),
						//									backgroundColor: '#fff',
						//									borderColor: 'rgba(255,151,0,1)',
						//									borderWidth: 1,
						//									borderRadius: 4,
						rich: {
							ranStyle: {
								color: 'rgba(255,151,0,1)',
								align: 'center',
								height: 20
							},

						},
						textStyle: {
							color: 'rgba(255,151,0,1)'
						}
					}
				},

			},
			areaStyle: {
				color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
					offset: 0,
					color: '#bfeeff'
				}, {
					offset: 1,
					color: '#fff'
				}]),
				origin: 'end'
			},
			data: []
		}]
	};

**Comment by zhuxinping** [comment]
![Uploading 2.png…]()

**Comment by zhuxinping** [comment]
如图
![1](https://user-images.githubusercontent.com/23069331/46130042-e048f600-c26a-11e8-93da-faddf71530b5.png)
![2](https://user-images.githubusercontent.com/23069331/46130043-e0e18c80-c26a-11e8-80b9-1609861e3b2c.png)

**Comment by l3ob** [comment]
没找到怎么取消mouseover的默认事件
实现思路是绑定mouseover事件和click事件
在mouseover事件中取消默认事件触发的高亮
在click事件中触发高亮

通过dispatchAction这个API，downplay就是取消高亮，highlight就是触发高亮
代码如下，可以复制到echarts的官方示例中测试
http://www.echartsjs.com/examples/editor.html?c=line-simple

```
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line',
        itemStyle: {
            normal: {
                color: 'rgba(0,170,255,1)'
            },
            emphasis: {
                color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                        offset: 0,
                        color: 'rgba(255,151,0,1)'
                    },
                    {
                        offset: 0.5,
                        color: 'rgba(255,151,0,0.8)'
                    },
                    {
                        offset: 1,
                        color: 'rgba(255,151,0,0.5)'
                    }
                ]),

                label: {
                    show: true,
                    formatter: [
                        ' {ranStyle|}第{c}名'
                    ].join("\n"),
                    rich: {
                        ranStyle: {
                            color: 'rgba(255,151,0,1)',
                            align: 'center',
                            height: 20
                        },

                    },
                    textStyle: {
                        color: 'rgba(255,151,0,1)'
                    }
                }
            }
        }
    }]
};

var currentIndex = -1;

myChart.on('finished', function() {
    if (currentIndex >= 0) {
        return;
    }

    myChart.dispatchAction({
        type: 'highlight',
        seriesIndex: 0,
        dataIndex: 6
    });

    currentIndex = 6;
});

myChart.on('mouseover', function(params) {
    if (params.dataIndex == currentIndex) {
        return;
    }

    myChart.dispatchAction({
        type: 'downplay',
        seriesIndex: params.seriesIndex,
        dataIndex: params.dataIndex
    });
});

myChart.on('click', function(params) {
    myChart.dispatchAction({
        type: 'downplay',
        seriesIndex: params.seriesIndex
    });

    myChart.dispatchAction({
        type: 'highlight',
        seriesIndex: params.seriesIndex,
        dataIndex: params.dataIndex
    });

    currentIndex = params.dataIndex;
});
```

相关文档：
- http://echarts.baidu.com/tutorial.html#ECharts%20%E4%B8%AD%E7%9A%84%E4%BA%8B%E4%BB%B6%E5%92%8C%E8%A1%8C%E4%B8%BA
- http://echarts.baidu.com/api.html#events
- http://echarts.baidu.com/api.html#action
