### ISSUE TITLE
axios下载的excel乱码，

### ISSUE THREAD

**Issue by zhangwudi886** [zhufengnodejs/question#3]
`
      const url = '/shiboexport/insi/report/export'
      axios({
        url,
        method: 'get',
        responseType: 'arraybuffer',  // 二进制流
        headers: {
          Authorization: 'Bearer 6f5d25c4-5a2f-4348-836b-c6e92861c266',
        }
      }).then(res => {
        console.log(res);
        const blob = new Blob([res.data], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8' });
        const a = document.createElement('a');
        const href = window.URL.createObjectURL(blob); // 创建链接对象
        a.href = href;
        a.download = 'fileName.xls';// 自定义文件名
        document.body.appendChild(a);
        a.click();
        window.URL.revokeObjectURL(href); // 移除链接对象
        document.body.removeChild(a); // 移除a元素
      })

`
直接放一起了，直接通过axios，get请求连接，地址已经做过代理，下载的内容已经通过bob对象处理成文件，但是结果一直都是乱码，不管responseType  是blob还是arraybuffer，结果都一样，
![image](https://user-images.githubusercontent.com/19159430/46209105-75c5b200-c35f-11e8-862e-17282381b4b3.png)
估计对于大家都是个小问题，权当日行善，日后好相见，，但是我不想通过直接打开新页面下载文件，感觉好low，有没有什么验证，还望大家有思路的提供个思路，

**Comment by zdddrszj** [comment]
文件下载既然用到后端接口，那后端 `Response Header` 设置
```
Content-Disposition: attachment; filename*=UTF-8''xxxxx
Content-Type: application/octet-stream
```
可以直接浏览器底部下载，并没有打开新页面呀

**Comment by l3ob** [comment]
应该就是编码问题 
需要给个能访问的地址 以及传一下正常的xls方便测试一下

**Comment by zhangwudi886** [comment]
> 应该就是编码问题
> 需要给个能访问的地址 以及传一下正常的xls方便测试一下

原来做过测试，postmen后面有一个send and download 可以直接下载，然后也没问题，总感觉是前端我的问题，但是最终也没解决，还是让后端改成了直接下载，感觉贼尴尬，太low了

**Comment by zhangwudi886** [comment]
> 文件下载既然用到后端接口，那后端 `Response Header` 设置
> 
> ```
> Content-Disposition: attachment; filename*=UTF-8''xxxxx
> Content-Type: application/octet-stream
> ```
> 可以直接浏览器底部下载，并没有打开新页面呀

其实已经设置过了 ，

**Comment by zhangwudi886** [comment]
先关闭了，，以后找时间自己弄一下，

**Comment by zhangwudi886** [comment]
多谢各位大佬
