### ISSUE TITLE
请问应该怎么配置才能给css和js打包到不同的文件中呢？ dist/static/js  dist/static/css  这样的目录

### ISSUE THREAD

**Issue by xlei1123** [zhufengnodejs/question#6]
[码云项目地址](https://gitee.com/xlei1123/bsym-webpack-ssr)

**Comment by zhangwudi886** [comment]
var ExtractTextPlugin = require('extract-text-webpack-plugin')
使用这个插件，[参考一下这个链接](https://diamont1001.github.io/webpack-summary/)
    new ExtractTextPlugin({
      filename: utils.assetsPath('css/[name].[contenthash].css')
    }),
下面这个结构自己设置，

**Comment by xlei1123** [comment]
> var ExtractTextPlugin = require('extract-text-webpack-plugin')
> 使用这个插件，[参考一下这个链接](https://diamont1001.github.io/webpack-summary/)
> new ExtractTextPlugin({
> filename: utils.assetsPath('css/[name].[contenthash].css')
> }),
> 下面这个结构自己设置，
谢谢，用了MiniCSSExtractPlugin 给filname路径写完整就好
